@startuml
title "1.3. Anwendungsfalldiagramm"
left to right direction
scale 1000
actor "Besucher\nJohn Johnes" as b
actor "Mitglied\nJane Johnes" as m
actor "Administrator\nBatuhan Avsar" as a

rectangle Account {
  usecase "Registrierung" as UC1
  usecase "Anmelde-Seite Sehen" as UC2
  usecase "Anmelden" as UC3
  usecase "Mitglieder verwalten" as UC8
}

rectangle Buchung {
  usecase "Buchung anfragen" as UC4
  usecase "Buchung überprüfen" as UC5
  usecase "Buchung stornieren" as UC6
  usecase "Buchung akzeptieren/ablehnen" as UC7
  usecase "Buchung verwalten" as UC9
  usecase "Buchungsmöglichkeiten sehen" as UC10
  usecase "Grund für Buchung angeben" as UC11
}

b --> UC1
b --> UC2
b --> UC3
a --> UC8

m --> UC4
m --> UC5
m --> UC6
a --> UC7
a --> UC9
m --> UC10
m --> UC11


@enduml